project_id: "663652"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*.{md, mdx, csv, json}
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /src/pages/learn/**/*.{md, mdx, csv, json}
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/learn/**/%original_file_name%
